import math

def nedelas_horoskopi(zodiac_sign):
    horoscope_messages = {
        'Auns': 'Uzdrīkstēšanās un enerģija, ar kādu ķersieties pie jebkura praktiska jautājuma risināšanas, būs apbrīnas vērta. Daudz ieguldot, daudz saņemsiet pretī -- ne tikai materiāli, bet arī emocionāli, jo iegūsiet pozitīvu pieredzi. Ar smaidu un labvēlību izturieties pret apkārtējiem, tad arī viņi pret jums tā izturēsies. Kārtojiet, pārkārtojiet un uzlabojiet pašu radīto dzīves telpu. Labvēlīgas dienas 6, 7; nelabvēlīga diena -- 1',
        'Vērsis': 'Centieties attaisnot uz jums liktās cerības, nevairieties no atbildības. Ja paši neuzskatīsiet par vajadzīgu, tad apstākļi un cilvēki liks saprast, ka par saviem vārdiem jāatbild un solījumi jāpilda. Rūpīgi izvērtējiet padarīto, pārdomājiet pieņemtos lēmumus, katru klupšanas akmeni uztveriet kā pacietības un pielāgošanās pārbaudījumu. Ja neizdodas tikt pie jauniem sasniegumiem, izmantojiet izdevību atgriezties pie nepaveiktiem darbiem. Labvēlīgas dienas -- 2, 5; nelabvēlīga diena -- 6. ',
        'Dvīņi': 'Klausiet sirdsbalsij, pret savu gribu neko nedariet, tālus un grūti sasniedzamus mērķus neizvēlieties, jo veiksme būs nenoturīga. Aktīva rosība var nedaudz noplakt, biežāk pārņems apcerīgs noskaņojums, pieaugs vajadzība pēc dziļākas situācijas analīzes. Pievērsieties kādas lietas vai procesa dziļākai izpētei, analīzei, paveiktā apkopšanai un secinājumu izdarīšanai. Labvēlīgas dienas -- 1, 7; nelabvēlīga diena -- 3. ',
        'Vēzis': 'Nebūs viegli sekot saviem ideāliem un izdarīt pareizo izvēli. Traucēs apjukums, neizlēmība, šaubas, būs grūti saglabāt objektivitāti, nepakļauties ietekmei no malas. Veiksmīgi aizsākušies procesi nedaudz iestrēgs, apstākļi mudinās pārskatīt pieņemtos lēmumus, izvērtēt kādas sadarbības lietderību, taču grūtības būs īslaicīgas, tieši tik, lai mobilizētos. Lūkojiet pēc dzīves gaišās puses. Labvēlīgas dienas -- 5, 6',
        'Lauva': 'Labi padosies analītiska rakstura darbi. Grūtāk būs tikt galā ar situācijām, kur nepieciešams kādu pārliecināt, iedvesmot vai kā citādi mijiedarboties, jo enerģija ātri izsīks un jums pašiem būs vajadzīgs uzmundrinājums. Jūsu interesēs ir ieturēt miermīlīgu politiku, jo lietderīgāk ir nelabvēli pārvērst sabiedrotajā, bet tas netraucēs kādam aizmuguriski vērpt intrigas pavedienus. Labvēlīga diena -- 2; nelabvēlīga diena -- 1. ',
        'Jaunava': 'Ja rodas nepieciešamība pēc papildu līdzekļiem vai nu tāpēc, lai sāktu mācības, vai dotos ceļojumā, nezaudējiet apņēmību un vēlmi īstenot iecerēto. Atliks visu mierīgi salikt pa plauktiņiem, lai saprastu, ka atrisināt problēmu var vienmēr. Svarīgi nepalikt vienam ar savām domām, bet meklēt cilvēkus, kas var palīdzēt -- ieguldītais pamazām atmaksāsies. Labvēlīga diena -- 3; nelabvēlīga diena -- 4. ',
        'Svari': 'Lai vilšanās un dažādas nebūšanas pēc iespējas mazāk ietekmētu virzību uz izraudzīto mērķi, meklējiet morālu atbalstu pie draugiem, smelieties spēku relaksējošās aktivitātēs. Jūsu plāns izdosies, ja vien objektīvi novērtēsiet apstākļus un nenokļūsiet maldīgu priekšstatu varā. Neizsakiet virspusēju viedokli, iedziļinieties tēmās, par kurām tiek runāts, vairieties no vienveidības. Labvēlīgas dienas -- 2, 5; nelabvēlīga diena -- 7. ',
        'Skorpions': 'Entuziastiski iesaistoties sabiedriskās aktivitātēs, izdosies atsvaidzināt savu radoša cilvēka reputāciju. Pozitīvu lādiņu sniegs tikšanās ar erudītiem, izlēmīgiem, darbīgi noskaņotiem cilvēkiem. Iedvesmojoties no viņiem, arī jūs kādam varat kļūt par atdarināšanas cienīgu paraugu. Ieviesiet korekcijas savā uzdevumu burtnīcā, jo būs racionāli dalīties pienākumos, kurus var veikt mazāk kvalificēts kolēģis. Labvēlīgas dienas -- 1, 3; nelabvēlīga diena -- 4.',
        'Strēlnieks': 'Saņemsiet nepamatotu kritiku par aktivitātēm procesos, kas no attāluma izskatās ne visai saprotami un viennozīmīgi tulkojami, būs jūsu patiesos motīvus zinās retais. Pieaugs vēlme pēc izklaidēm, ceļojumiem, jauniem iespaidiem un piedzīvojumiem. Ideju pārpilnība var radīt nelielu sajukumu, jo būs grūti saprast, kuru no tām īstenot uzreiz, kuru -- atlikt uz vēlāku laiku. Labvēlīgas dienas -- 5, 7; nelabvēlīga diena -- 6. ',
        'Mežāzis': 'Attiecībās iespējami emocionāli kāpumi un kritumi. Kamēr šaubīsieties un nebūsiet pārliecināti par savu jūtu noturīgumu, atstāsiet neizlēmīga, neapmierināta cilvēka iespaidu, taču atliks kādam vairāk izrādīt uzmanības, uzklausīt un novērtēt, un jūs būsiet gatavi atvērties, ļaujoties pozitīvu emociju vilnim. Risinot praktiskus jautājumus, problēmas var rasties iesīkstējušu uzskatu dēļ. Labvēlīga diena -- 2; nelabvēlīga diena -- 1',
        'Ūdensvīrs': 'Kopā ar ģimeni un tuviniekiem pavadītie brīži ļaus izbaudīt stabilitātes un drošības izjūtu, kam šajā saspringtajā un pārmaiņu pilnajā laikā var izrādīties liela nozīme. Apstākļi būs labvēlīgi praktisku, ar mājām un ģimeni saistītu jautājumu risināšanai. Dzīvokļa remonts, pārkārtojumi un citas saimnieciskas aktivitātes aizņems lielu daļu uzmanības. jo aktīvāk rosīsieties, jo vairāk izdosies paveikt. Labvēlīgas dienas -- 4, 7; nelabvēlīga diena -- 6. ',
        'Zivis': 'Pievilcīgu apkārtējo acīs jūs padarīs ne vien prasme piekāpties un rast kompromisus, bet arī personības šarms. Tas piesaistīs apkārtējo uzmanību un pulcēs ap jums azartiskus, dzīvespriecīgus cilvēkus. Viņu mudināti, varat iedvesmoties drosmīgai rīcībai un gūt negaidīti labus radošus panākumus. Nemitīgās rosības jūklī tomēr atvēliet brīdi sev. Pastiprinātu uzmanību veltiet pašsajūtai. Labvēlīga diena -- 3; nelabvēlīga diena -- 1. ',
    }

    default_horoscope = 'Uzdrīkstēšanās un enerģija, ar kādu ķersieties pie jebkura praktiska jautājuma risināšanas, būs apbrīnas vērta. Daudz ieguldot, daudz saņemsiet pretī -- ne tikai materiāli, bet arī emocionāli, jo iegūsiet pozitīvu pieredzi. Ar smaidu un labvēlību izturieties pret apkārtējiem, tad arī viņi pret jums tā izturēsies. Kārtojiet, pārkārtojiet un uzlabojiet pašu radīto dzīves telpu. Labvēlīgas dienas 6, 7; nelabvēlīga diena -- 1'  # Default for 'Auns'
    default_horoscope = 'Centieties attaisnot uz jums liktās cerības, nevairieties no atbildības. Ja paši neuzskatīsiet par vajadzīgu, tad apstākļi un cilvēki liks saprast, ka par saviem vārdiem jāatbild un solījumi jāpilda. Rūpīgi izvērtējiet padarīto, pārdomājiet pieņemtos lēmumus, katru klupšanas akmeni uztveriet kā pacietības un pielāgošanās pārbaudījumu. Ja neizdodas tikt pie jauniem sasniegumiem, izmantojiet izdevību atgriezties pie nepaveiktiem darbiem. Labvēlīgas dienas -- 2, 5; nelabvēlīga diena -- 6. '     # Default for 'Vērsis'
    default_horoscope = 'Klausiet sirdsbalsij, pret savu gribu neko nedariet, tālus un grūti sasniedzamus mērķus neizvēlieties, jo veiksme būs nenoturīga. Aktīva rosība var nedaudz noplakt, biežāk pārņems apcerīgs noskaņojums, pieaugs vajadzība pēc dziļākas situācijas analīzes. Pievērsieties kādas lietas vai procesa dziļākai izpētei, analīzei, paveiktā apkopšanai un secinājumu izdarīšanai. Labvēlīgas dienas -- 1, 7; nelabvēlīga diena -- 3. '  # Default for 'Dvīņī'
    default_horoscope = 'Nebūs viegli sekot saviem ideāliem un izdarīt pareizo izvēli. Traucēs apjukums, neizlēmība, šaubas, būs grūti saglabāt objektivitāti, nepakļauties ietekmei no malas. Veiksmīgi aizsākušies procesi nedaudz iestrēgs, apstākļi mudinās pārskatīt pieņemtos lēmumus, izvērtēt kādas sadarbības lietderību, taču grūtības būs īslaicīgas, tieši tik, lai mobilizētos. Lūkojiet pēc dzīves gaišās puses. Labvēlīgas dienas -- 5, 6'   # Default for 'Vēzis'
    default_horoscope = 'Labi padosies analītiska rakstura darbi. Grūtāk būs tikt galā ar situācijām, kur nepieciešams kādu pārliecināt, iedvesmot vai kā citādi mijiedarboties, jo enerģija ātri izsīks un jums pašiem būs vajadzīgs uzmundrinājums. Jūsu interesēs ir ieturēt miermīlīgu politiku, jo lietderīgāk ir nelabvēli pārvērst sabiedrotajā, bet tas netraucēs kādam aizmuguriski vērpt intrigas pavedienus. Labvēlīga diena -- 2; nelabvēlīga diena -- 1. '   # Default for 'Lauva'
    default_horoscope = 'Ja rodas nepieciešamība pēc papildu līdzekļiem vai nu tāpēc, lai sāktu mācības, vai dotos ceļojumā, nezaudējiet apņēmību un vēlmi īstenot iecerēto. Atliks visu mierīgi salikt pa plauktiņiem, lai saprastu, ka atrisināt problēmu var vienmēr. Svarīgi nepalikt vienam ar savām domām, bet meklēt cilvēkus, kas var palīdzēt -- ieguldītais pamazām atmaksāsies. Labvēlīga diena -- 3; nelabvēlīga diena -- 4. '   # Default for 'Jaunava'
    default_horoscope = 'Lai vilšanās un dažādas nebūšanas pēc iespējas mazāk ietekmētu virzību uz izraudzīto mērķi, meklējiet morālu atbalstu pie draugiem, smelieties spēku relaksējošās aktivitātēs. Jūsu plāns izdosies, ja vien objektīvi novērtēsiet apstākļus un nenokļūsiet maldīgu priekšstatu varā. Neizsakiet virspusēju viedokli, iedziļinieties tēmās, par kurām tiek runāts, vairieties no vienveidības. Labvēlīgas dienas -- 2, 5; nelabvēlīga diena -- 7. '  # Default for 'Svari'
    default_horoscope = 'Entuziastiski iesaistoties sabiedriskās aktivitātēs, izdosies atsvaidzināt savu radoša cilvēka reputāciju. Pozitīvu lādiņu sniegs tikšanās ar erudītiem, izlēmīgiem, darbīgi noskaņotiem cilvēkiem. Iedvesmojoties no viņiem, arī jūs kādam varat kļūt par atdarināšanas cienīgu paraugu. Ieviesiet korekcijas savā uzdevumu burtnīcā, jo būs racionāli dalīties pienākumos, kurus var veikt mazāk kvalificēts kolēģis. Labvēlīgas dienas -- 1, 3; nelabvēlīga diena -- 4.'  # Default for 'Skorpions'
    default_horoscope = 'Saņemsiet nepamatotu kritiku par aktivitātēm procesos, kas no attāluma izskatās ne visai saprotami un viennozīmīgi tulkojami, būs jūsu patiesos motīvus zinās retais. Pieaugs vēlme pēc izklaidēm, ceļojumiem, jauniem iespaidiem un piedzīvojumiem. Ideju pārpilnība var radīt nelielu sajukumu, jo būs grūti saprast, kuru no tām īstenot uzreiz, kuru -- atlikt uz vēlāku laiku. Labvēlīgas dienas -- 5, 7; nelabvēlīga diena -- 6. '  # Default for 'Strēlnieks'
    default_horoscope = 'Attiecībās iespējami emocionāli kāpumi un kritumi. Kamēr šaubīsieties un nebūsiet pārliecināti par savu jūtu noturīgumu, atstāsiet neizlēmīga, neapmierināta cilvēka iespaidu, taču atliks kādam vairāk izrādīt uzmanības, uzklausīt un novērtēt, un jūs būsiet gatavi atvērties, ļaujoties pozitīvu emociju vilnim. Risinot praktiskus jautājumus, problēmas var rasties iesīkstējušu uzskatu dēļ. Labvēlīga diena -- 2; nelabvēlīga diena -- 1'   # Default for 'Mežāzis'
    default_horoscope = 'Kopā ar ģimeni un tuviniekiem pavadītie brīži ļaus izbaudīt stabilitātes un drošības izjūtu, kam šajā saspringtajā un pārmaiņu pilnajā laikā var izrādīties liela nozīme. Apstākļi būs labvēlīgi praktisku, ar mājām un ģimeni saistītu jautājumu risināšanai. Dzīvokļa remonts, pārkārtojumi un citas saimnieciskas aktivitātes aizņems lielu daļu uzmanības. jo aktīvāk rosīsieties, jo vairāk izdosies paveikt. Labvēlīgas dienas -- 4, 7; nelabvēlīga diena -- 6. '  # Default for 'Ūdensvīrs'
    default_horoscope = 'Pievilcīgu apkārtējo acīs jūs padarīs ne vien prasme piekāpties un rast kompromisus, bet arī personības šarms. Tas piesaistīs apkārtējo uzmanību un pulcēs ap jums azartiskus, dzīvespriecīgus cilvēkus. Viņu mudināti, varat iedvesmoties drosmīgai rīcībai un gūt negaidīti labus radošus panākumus. Nemitīgās rosības jūklī tomēr atvēliet brīdi sev. Pastiprinātu uzmanību veltiet pašsajūtai. Labvēlīga diena -- 3; nelabvēlīga diena -- 1. '  # Default for 'Zivs'

    return horoscope_messages.get(zodiac_sign, default_horoscope)

# Ask for a specific zodiac sign
user_sign = input('Ievadiet zodiaka zīmi: ')
horoscope = nedelas_horoskopi(user_sign.capitalize())
print(f'Horoskops zodiakam {user_sign.capitalize()}: {horoscope}')
